name: ACR Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: lsc-sde/lsc-sde/.github/workflows/acr-build.yaml@main
    with:
      repository: controllers
      imageName: aks-dns-operator
      environment: Sandbox