name: ACR Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: lsc-sde/lsc-sde/.github/workflows/acr-build.yaml@main
    with:
      repository: controllers
      imageName: aks-dns-controller
      azureKeyvault: ${{ vars.sandbox_az_keyvault }}
    secrets:
      azureCredentials: ${{ secrets.sandbox_az_credentials }}