name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: aks-dns-operator
      directory: docker/aks-dns-operator
    secrets: inherit
